from brownie import *

def main():
    deploy_acct = accounts.load("ropsten")
    congress = Contract("MOC") 
    congress.mintMOC("Richard Shelby", 'ALSEN1', "https://wikipedia.org/wiki/Richard_Shelby", {'from': deploy_acct})
    congress.mintMOC("Tommy Tuberville", 'ALSEN2', "https://wikipedia.org/wiki/Tommy_Tuberville", {'from': deploy_acct})
    congress.mintMOC("Lisa Murkowski", 'AKSEN1', "https://wikipedia.org/wiki/Lisa_Murkowski", {'from': deploy_acct})
    congress.mintMOC("Dan Sullivan", 'AKSEN2', "https://wikipedia.org/wiki/Dan_Sullivan", {'from': deploy_acct})
    congress.mintMOC("Kyrsten Sinema", 'AZSEN1', "https://wikipedia.org/wiki/Kyrsten_Sinema", {'from': deploy_acct})
    congress.mintMOC("Mark Kelly", 'AZSEN2', "https://wikipedia.org/wiki/Mark_Kelly", {'from': deploy_acct})
    congress.mintMOC("John Boozman", 'ARSEN1', "https://wikipedia.org/wiki/John_Boozman", {'from': deploy_acct})
    congress.mintMOC("Tom Cotton", 'ARSEN2', "https://wikipedia.org/wiki/Tom_Cotton", {'from': deploy_acct})
    congress.mintMOC("Dianne Feinstein", 'CASEN1', "https://wikipedia.org/wiki/Dianne_Feinstein", {'from': deploy_acct})
    congress.mintMOC("Alex Padilla", 'CASEN2', "https://wikipedia.org/wiki/Alex_Padilla", {'from': deploy_acct})
    congress.mintMOC("Michael Bennet", 'COSEN1', "https://wikipedia.org/wiki/Michael_Bennet", {'from': deploy_acct})
    congress.mintMOC("John Hickenlooper", 'COSEN2', "https://wikipedia.org/wiki/John_Hickenlooper", {'from': deploy_acct})
    congress.mintMOC("Richard Blumenthal", 'CTSEN1', "https://wikipedia.org/wiki/Richard_Blumenthal", {'from': deploy_acct})
    congress.mintMOC("Chris Murphy", 'CTSEN2', "https://wikipedia.org/wiki/Chris_Murphy", {'from': deploy_acct})
    congress.mintMOC("Tom Carper", 'DESEN1', "https://wikipedia.org/wiki/Tom_Carper", {'from': deploy_acct})
    congress.mintMOC("Chris Coons", 'DESEN2', "https://wikipedia.org/wiki/Chris_Coons", {'from': deploy_acct})
    congress.mintMOC("Marco Rubio", 'FLSEN1', "https://wikipedia.org/wiki/Marco_Rubio", {'from': deploy_acct})
    congress.mintMOC("Rick Scott", 'FLSEN2', "https://wikipedia.org/wiki/Rick_Scott", {'from': deploy_acct})
    congress.mintMOC("Jon Ossoff", 'GASEN1', "https://wikipedia.org/wiki/Jon_Ossoff", {'from': deploy_acct})
    congress.mintMOC("Raphael Warnock", 'GASEN2', "https://wikipedia.org/wiki/Raphael_Warnock", {'from': deploy_acct})
    congress.mintMOC("Brian Schatz", 'HISEN1', "https://wikipedia.org/wiki/Brian_Schatz", {'from': deploy_acct})
    congress.mintMOC("Mazie Hirono", 'HISEN2', "https://wikipedia.org/wiki/Mazie_Hirono", {'from': deploy_acct})
    congress.mintMOC("Mike Crapo", 'IDSEN1', "https://wikipedia.org/wiki/Mike_Crapo", {'from': deploy_acct})
    congress.mintMOC("Jim Risch", 'IDSEN2', "https://wikipedia.org/wiki/Jim_Risch", {'from': deploy_acct})
    congress.mintMOC("Dick Durbin", 'ILSEN1', "https://wikipedia.org/wiki/Dick_Durbin", {'from': deploy_acct})
    congress.mintMOC("Tammy Duckworth", 'ILSEN2', "https://wikipedia.org/wiki/Tammy_Duckworth", {'from': deploy_acct})
    congress.mintMOC("Todd Young", 'INSEN1', "https://wikipedia.org/wiki/Todd_Young", {'from': deploy_acct})
    congress.mintMOC("Mike Braun", 'INSEN2', "https://wikipedia.org/wiki/Mike_Braun", {'from': deploy_acct})
    congress.mintMOC("Chuck Grassley", 'IASEN1', "https://wikipedia.org/wiki/Chuck_Grassley", {'from': deploy_acct})
    congress.mintMOC("Joni Ernst", 'IASEN2', "https://wikipedia.org/wiki/Joni_Ernst", {'from': deploy_acct})
    congress.mintMOC("Jerry Moran", 'KSSEN1', "https://wikipedia.org/wiki/Jerry_Moran", {'from': deploy_acct})
    congress.mintMOC("Roger Marshall", 'KSSEN2', "https://wikipedia.org/wiki/Roger_Marshall", {'from': deploy_acct})
    congress.mintMOC("Mitch McConnell", 'KYSEN1', "https://wikipedia.org/wiki/Mitch_McConnell", {'from': deploy_acct})
    congress.mintMOC("Rand Paul", 'KYSEN2', "https://wikipedia.org/wiki/Rand_Paul", {'from': deploy_acct})
    congress.mintMOC("Bill Cassidy", 'LASEN1', "https://wikipedia.org/wiki/Bill_Cassidy", {'from': deploy_acct})
    congress.mintMOC("John Neely Kennedy", 'LASEN2', "https://wikipedia.org/wiki/John_Neely_Kennedy", {'from': deploy_acct})
    congress.mintMOC("Susan Collins", 'MESEN1', "https://wikipedia.org/wiki/Susan_Collins", {'from': deploy_acct})
    congress.mintMOC("Angus King Jr.", 'MESEN2', "https://wikipedia.org/wiki/Angus_King_Jr.", {'from': deploy_acct})
    congress.mintMOC("Ben Cardin", 'MDSEN1', "https://wikipedia.org/wiki/Ben_Cardin", {'from': deploy_acct})
    congress.mintMOC("Chris Van Hollen", 'MDSEN2', "https://wikipedia.org/wiki/Chris_Van_Hollen", {'from': deploy_acct})
    congress.mintMOC("Elizabeth Warren", 'MASEN1', "https://wikipedia.org/wiki/Elizabeth_Warren", {'from': deploy_acct})
    congress.mintMOC("Ed Markey", 'MASEN2', "https://wikipedia.org/wiki/Ed_Markey", {'from': deploy_acct})
    congress.mintMOC("Debbie Stabenow", 'MISEN1', "https://wikipedia.org/wiki/Debbie_Stabenow", {'from': deploy_acct})
    congress.mintMOC("Gary Peters", 'MISEN2', "https://wikipedia.org/wiki/Gary_Peters", {'from': deploy_acct})
    congress.mintMOC("Amy Klobuchar", 'MNSEN1', "https://wikipedia.org/wiki/Amy_Klobuchar", {'from': deploy_acct})
    congress.mintMOC("Tina Smith", 'MNSEN2', "https://wikipedia.org/wiki/Tina_Smith", {'from': deploy_acct})
    congress.mintMOC("Roger Wicker", 'MSSEN1', "https://wikipedia.org/wiki/Roger_Wicker", {'from': deploy_acct})
    congress.mintMOC("Cindy Hyde-Smith", 'MSSEN2', "https://wikipedia.org/wiki/Cindy_Hyde-Smith", {'from': deploy_acct})
    congress.mintMOC("Roy Blunt", 'MOSEN1', "https://wikipedia.org/wiki/Roy_Blunt", {'from': deploy_acct})
    congress.mintMOC("Josh Hawley", 'MOSEN2', "https://wikipedia.org/wiki/Josh_Hawley", {'from': deploy_acct})
    congress.mintMOC("Jon Tester", 'MTSEN1', "https://wikipedia.org/wiki/Jon_Tester", {'from': deploy_acct})
    congress.mintMOC("Steve Daines", 'MTSEN2', "https://wikipedia.org/wiki/Steve_Daines", {'from': deploy_acct})
    congress.mintMOC("Deb Fischer", 'NESEN1', "https://wikipedia.org/wiki/Deb_Fischer", {'from': deploy_acct})
    congress.mintMOC("Ben Sasse", 'NESEN2', "https://wikipedia.org/wiki/Ben_Sasse", {'from': deploy_acct})
    congress.mintMOC("Catherine Cortez Masto", 'NVSEN1', "https://wikipedia.org/wiki/Catherine_Cortez_Masto", {'from': deploy_acct})
    congress.mintMOC("Jacky Rosen", 'NVSEN2', "https://wikipedia.org/wiki/Jacky_Rosen", {'from': deploy_acct})
    congress.mintMOC("Jeanne Shaheen", 'NHSEN1', "https://wikipedia.org/wiki/Jeanne_Shaheen", {'from': deploy_acct})
    congress.mintMOC("Maggie Hassan", 'NHSEN2', "https://wikipedia.org/wiki/Maggie_Hassan", {'from': deploy_acct})
    congress.mintMOC("Bob Menendez", 'NJSEN1', "https://wikipedia.org/wiki/Bob_Menendez", {'from': deploy_acct})
    congress.mintMOC("Cory Booker", 'NJSEN2', "https://wikipedia.org/wiki/Cory_Booker", {'from': deploy_acct})
    congress.mintMOC("Martin Heinrich", 'NMSEN1', "https://wikipedia.org/wiki/Martin_Heinrich", {'from': deploy_acct})
    congress.mintMOC("Ben Ray Luján", 'NMSEN2', "https://wikipedia.org/wiki/Ben_Ray_Luján", {'from': deploy_acct})
    congress.mintMOC("Chuck Schumer", 'NYSEN1', "https://wikipedia.org/wiki/Chuck_Schumer", {'from': deploy_acct})
    congress.mintMOC("Kirsten Gillibrand", 'NYSEN2', "https://wikipedia.org/wiki/Kirsten_Gillibrand", {'from': deploy_acct})
    congress.mintMOC("Richard Burr", 'NCSEN1', "https://wikipedia.org/wiki/Richard_Burr", {'from': deploy_acct})
    congress.mintMOC("Thom Tillis", 'NCSEN2', "https://wikipedia.org/wiki/Thom_Tillis", {'from': deploy_acct})
    congress.mintMOC("John Hoeven", 'NDSEN1', "https://wikipedia.org/wiki/John_Hoeven", {'from': deploy_acct})
    congress.mintMOC("Kevin Cramer", 'NDSEN2', "https://wikipedia.org/wiki/Kevin_Cramer", {'from': deploy_acct})
    congress.mintMOC("Sherrod Brown", 'OHSEN1', "https://wikipedia.org/wiki/Sherrod_Brown", {'from': deploy_acct})
    congress.mintMOC("Rob Portman", 'OHSEN2', "https://wikipedia.org/wiki/Rob_Portman", {'from': deploy_acct})
    congress.mintMOC("Jim Inhofe", 'OKSEN1', "https://wikipedia.org/wiki/Jim_Inhofe", {'from': deploy_acct})
    congress.mintMOC("James Lankford", 'OKSEN2', "https://wikipedia.org/wiki/James_Lankford", {'from': deploy_acct})
    congress.mintMOC("Ron Wyden", 'ORSEN1', "https://wikipedia.org/wiki/Ron_Wyden", {'from': deploy_acct})
    congress.mintMOC("Jeff Merkley", 'ORSEN2', "https://wikipedia.org/wiki/Jeff_Merkley", {'from': deploy_acct})
    congress.mintMOC("Bob Casey Jr.", 'PASEN1', "https://wikipedia.org/wiki/Bob_Casey_Jr.", {'from': deploy_acct})
    congress.mintMOC("Pat Toomey", 'PASEN2', "https://wikipedia.org/wiki/Pat_Toomey", {'from': deploy_acct})
    congress.mintMOC("Jack Reed", 'RISEN1', "https://wikipedia.org/wiki/Jack_Reed", {'from': deploy_acct})
    congress.mintMOC("Sheldon Whitehouse", 'RISEN2', "https://wikipedia.org/wiki/Sheldon_Whitehouse", {'from': deploy_acct})
    congress.mintMOC("Lindsey Graham", 'SCSEN1', "https://wikipedia.org/wiki/Lindsey_Graham", {'from': deploy_acct})
    congress.mintMOC("Tim Scott", 'SCSEN2', "https://wikipedia.org/wiki/Tim_Scott", {'from': deploy_acct})
    congress.mintMOC("John Thune", 'SDSEN1', "https://wikipedia.org/wiki/John_Thune", {'from': deploy_acct})
    congress.mintMOC("Mike Rounds", 'SDSEN2', "https://wikipedia.org/wiki/Mike_Rounds", {'from': deploy_acct})
    congress.mintMOC("Marsha Blackburn", 'TNSEN1', "https://wikipedia.org/wiki/Marsha_Blackburn", {'from': deploy_acct})
    congress.mintMOC("Bill Hagerty", 'TNSEN2', "https://wikipedia.org/wiki/Bill_Hagerty", {'from': deploy_acct})
    congress.mintMOC("John Cornyn", 'TXSEN1', "https://wikipedia.org/wiki/John_Cornyn", {'from': deploy_acct})
    congress.mintMOC("Ted Cruz", 'TXSEN2', "https://wikipedia.org/wiki/Ted_Cruz", {'from': deploy_acct})
    congress.mintMOC("Mike Lee", 'UTSEN1', "https://wikipedia.org/wiki/Mike_Lee", {'from': deploy_acct})
    congress.mintMOC("Mitt Romney", 'UTSEN2', "https://wikipedia.org/wiki/Mitt_Romney", {'from': deploy_acct})
    congress.mintMOC("Patrick Leahy", 'VTSEN1', "https://wikipedia.org/wiki/Patrick_Leahy", {'from': deploy_acct})
    congress.mintMOC("Bernie Sanders", 'VTSEN2', "https://wikipedia.org/wiki/Bernie_Sanders", {'from': deploy_acct})
    congress.mintMOC("Mark Warner", 'VASEN1', "https://wikipedia.org/wiki/Mark_Warner", {'from': deploy_acct})
    congress.mintMOC("Tim Kaine", 'VASEN2', "https://wikipedia.org/wiki/Tim_Kaine", {'from': deploy_acct})
    congress.mintMOC("Patty Murray", 'WASEN1', "https://wikipedia.org/wiki/Patty_Murray", {'from': deploy_acct})
    congress.mintMOC("Maria Cantwell", 'WASEN2', "https://wikipedia.org/wiki/Maria_Cantwell", {'from': deploy_acct})
    congress.mintMOC("Joe Manchin", 'WVSEN1', "https://wikipedia.org/wiki/Joe_Manchin", {'from': deploy_acct})
    congress.mintMOC("Shelley Moore Capito", 'WVSEN2', "https://wikipedia.org/wiki/Shelley_Moore_Capito", {'from': deploy_acct})
    congress.mintMOC("Ron Johnson", 'WISEN1', "https://wikipedia.org/wiki/Ron_Johnson", {'from': deploy_acct})
    congress.mintMOC("Tammy Baldwin", 'WISEN2', "https://wikipedia.org/wiki/Tammy_Baldwin", {'from': deploy_acct})
    congress.mintMOC("John Barrasso", 'WYSEN1', "https://wikipedia.org/wiki/John_Barrasso", {'from': deploy_acct})
    congress.mintMOC("Cynthia Lummis", 'WYSEN2', "https://wikipedia.org/wiki/Cynthia_Lummis", {'from': deploy_acct})
